model:
  net:
    class_path: modules.kms_multimag_hrrr.ForeHRRR
    init_args:
      # Input infos
      multi_list: [False, True, False, False, False] # stands for ['era5', 'hrrr', 'goes', 'mrms', 'station']
      num_variables: [59, 69, 4, 1, 5]
      spatial_sizes: [32, 320, 320, 960, 320] # crop_size = 32
      num_in_frames: [2, 2, 6, 6, 4]
      num_out_frames: [0, 1, 0, 0, 0] 
      latent_size: 80
      embed_dim: 1024
      init_dim: 192
      hidden_dim: 192

      # Tricks
      add_grad_loss: True
      use_geo: False
      use_old_geo: False
      use_time: False
      geo_dim: 5
      attend_space: False
      attend_time: False
      use_interpolation: True
      interpolate_mode: 'bilinear'
      eval_size: 320
      # Tasks
      loss_type: 'mse'
      use_weights: False
      # masked_picked_idx: [0, 1, 2, 3, 
      #                     4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 
      #                     15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 
      #                     26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 
      #                     37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 
      #                     48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58]
      # log_picked_idx: [0, 1, 2, 3, 
      #                 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 
      #                 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 
      #                 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 
      #                 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 
      #                 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]
      # # out_groups: [1, 1, 1, 1, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6]
      # out_groups: [1, 1, 1, 1, 11, 11, 11, 11, 11]


      # all 69 variables
      masked_picked_idx: [0, 1, 2, 3, 
                          4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 
                          17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
                          30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
                          43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
                          56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68
                          ]
      log_picked_idx: [0, 1, 2, 3, 
                      4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 
                      17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 
                      30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 
                      43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 
                      56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68]
      # out_groups: [1, 1, 2, 13, 13, 13, 13, 13]
      out_groups: [1, 1, 2, 13, 13, 13, 13, 13]

      pred_delta: True

      # Swin v2 block paramaters
      temporal_dim: 1024
      temporal_depth: 48
      num_heads: 16
      temporal_window_size:  8
      mlp_ratio: 4.
      qkv_bias: True
      drop_rate: 0.02
      attn_drop_rate: 0.02
      drop_path_rate: 0.02
      layer_norm: True
      use_checkpoint: False

  restart_path: ""
  opt_name: adamw
  # opt_name: rmsprop
  rmsprop_alpha: 0.99 # for rmsprop optimizer
  lr: 3e-5
  beta_1: 0.9 # for adam optimizer
  beta_2: 0.999 # for adam optimizer
  weight_decay: 0.02
  warmup_steps: 3000
  warmup_start_lr: 0
  eta_min: 1e-7
  # dataset configs
  datasets: ['hrrr']
  # not_used_levels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13] # For HRRR, we don't use 5000 and 10000 pressure levels
  # not_used_levels: [1, 2] # For HRRR, we don't use 5000 and 10000 pressure levels
  not_used_levels: [] # For HRRR, we don't use 5000 and 10000 pressure levels
  norm_path: './'
  data_type: 32
  max_steps: 50000
  need_rescale_grad: False

