# pytorch_lightning==2.0.4
seed_everything: 42
trainer:
  default_root_dir: /weather-blob/pengxiao/kms_logs
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "step"
    - class_path: pytorch_lightning.callbacks.RichModelSummary
      init_args:
        max_depth: -1

  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: auto
  enable_progress_bar: true
  overfit_batches: 0.0
  check_val_every_n_epoch: 2
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: 500
  limit_test_batches: 0
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 50
  accelerator: gpu
  strategy: ddp_find_unused_parameters_false
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: true
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  detect_anomaly: false
  plugins: null
  inference_mode: true
